name: LaunchArc
options:
  bundleIdPrefix: com.something
  generateEmptyDirectories: true
targets:
  LaunchArc:
    type: application
    platform: iOS
    deploymentTarget: "17.4"
    sources: [LaunchArc]
    settings:
      base:
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: 5.0
        ENABLE_USER_SCRIPT_SANDBOXING: NO
